# Generated by Django 5.2.7 on 2025-11-06 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_user_address_user_business_name_user_business_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
