# Generated by Django 5.2.7 on 2025-11-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_simplebook'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SimpleBook',
        ),
        migrations.RemoveField(
            model_name='book',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
