# Generated by Django 5.2.7 on 2025-11-08 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_seller'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
